# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-22 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mzazagram', '0003_image_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageLikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageid', models.IntegerField()),
                ('liker', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
