# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-23 06:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mzazagram', '0004_auto_20180722_0858'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageLikes',
        ),
    ]
